# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

# linter configurations
COPYPASTE_JSCPD_CONFIG_FILE: ./configs/.jscpd.json
SPELL_CSPELL_CONFIG_FILE: ./configs/.cspell.json
