# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

DISABLE_LINTERS:
  # devskim is probably going to be removed in MegaLinter v8, so don't bother addressing permission issues
  # https://github.com/oxsecurity/megalinter/issues/2849
  - REPOSITORY_DEVSKIM

SHOW_ELAPSED_TIME: true

FILEIO_REPORTER: false

POST_COMMANDS:
  - command: chown --recursive $USER_ID:$GROUP_ID /tmp/lint
    cwd: workspace

# linter configurations
COPYPASTE_JSCPD_CONFIG_FILE: ./configs/.jscpd.json
GO_GOLANGCI_LINT_CONFIG_FILE: ./configs/.golangci.yml
SPELL_CSPELL_CONFIG_FILE: ./configs/.cspell.json
